version: "3"
services:
  php:
    image: gkephart/alpine-php-apache
    ports:
      - 80:80
    environment:
      - APACHE_SERVER_NAME=alpine.docker.localhost
    volumes:
      - ./index.php:/app/public/index.php

